### ISSUE TITLE
Failed to install nfd with this dockerfile on ubuntu 14.04

### ISSUE THREAD

**Issue by ISHITADG** [felixrabe-attic/named-data-education--ndn-with-docker#8]
I have attached the error I receive below. 
Does anyone know why this seems to occur?
In case the image is not visible , the error message reads as follows: 

> OK: certificate with name [/localhost/daemons/nfd/KEY/%5B%C7%CE%F8~%E3%C5e/self/%FD%00%00%01d%02%2F%86q] has been successfully installed
> Failed to set capabilities on file `/usr/bin/nfd' (Invalid argument)
> The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file
> dpkg: error processing package nfd (--configure):
>  subprocess installed post-installation script returned error exit status 1
> Processing triggers for libc-bin (2.19-0ubuntu6.14) ...
> Processing triggers for ureadahead (0.100.0-16) ...
> Errors were encountered while processing:
>  nfd
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> The command '/bin/sh -c apt-get install -y nfd' returned a non-zero code: 100
> 

<img width="1280" alt="screen shot 2018-06-15 at 2 49 34 am" src="https://user-images.githubusercontent.com/10891874/41454892-21387434-7049-11e8-9119-844ff2c86a59.png">

**Comment by felixrabe** [comment]
Hi @ISHITADG 

I'm sorry I haven't used Docker nor NDN since about 2015, so I don't have a setup to reprocude your issue, nor do I have up-to-date knowledge about either to help you. Also, because both Docker and NDN have progressed since I last worked on this repo, I'd be surprised if it was still useful at all.

Try contacting the http://named-data.net/ mailing lists and/or check out the Docker hub at https://hub.docker.com/ to see if someone else got more recent Docker images for NDN.

**Comment by yoursunny** [comment]
NFD’s minimal system requirement is Ubuntu 16.04, and no longer supports 14.04. However, this issue isn’t caused by that, because 0.6.2 is the last release supporting Ubuntu 14.04. Nevertheless, I would not investigate this.

Two alternatives using newer base images:
https://github.com/yoursunny/docker-nfd
https://github.com/peetonn/ndn-docker by @peetonn
Both compile from source code so they’ll take longer to build.

**Comment by felixrabe** [comment]
Thx @yoursunny
